version: '3.7'

services:
  grpc: &grpc
    image: grpc-tools
    volumes:
    - ./:/go-grpc-example

  grpc-gen:
    <<: *grpc
    user: ${CURRENT_UID}
    command: |
      sh -c "
        # generate stub files
        protoc -I /go-grpc-example --go_out=/ /go-grpc-example/internal/proto-files/domain/repository.proto

        # plugins=grpc will add special methods required to run grpc service
        protoc -I /go-grpc-example --go_out=plugins=grpc:/ /go-grpc-example/internal/proto-files/service/repository-service.proto
      "

  server:
    image: go-grpc-example
    command: go run cmd/grpc/server/main.go

  client:
    image: go-grpc-example
    command: go run cmd/grpc/client/main.go